package projetolocadora;

import dao.LocacaoDAO;
import dao.PagamentoDAO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.List;
/**
 *
 * @author Thiago Henrique
 */
public class TelaPagamento extends javax.swing.JFrame {
    private LocacaoDAO locacaoDAO = new LocacaoDAO();
    private PagamentoDAO pagamentoDAO = new PagamentoDAO();
    
    private List<Locacao> locacoes;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPagamento.class.getName());

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(
        javax.swing.WindowConstants.DISPOSE_ON_CLOSE
    );

    comboFormaPagamento.removeAllItems();

    comboFormaPagamento.addItem("Pix");
    comboFormaPagamento.addItem("Cartão");
    comboFormaPagamento.addItem("Dinheiro");

    tabelaPagamentos.setModel(
    new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "Cliente",
            "Carro",
            "Dias",
            "Valor",
            "Forma"
        }
    )
);

    tabelaPagamentos.getColumnModel().getColumn(0).setPreferredWidth(160);
    tabelaPagamentos.getColumnModel().getColumn(1).setPreferredWidth(150);
    tabelaPagamentos.getColumnModel().getColumn(2).setPreferredWidth(30);
    tabelaPagamentos.getColumnModel().getColumn(3).setPreferredWidth(60);
    tabelaPagamentos.getColumnModel().getColumn(4).setPreferredWidth(50);
    lblValor.setText("R$ 0,00");
    carregarLocacoes();
    carregarPagamentos();
}

        private void carregarLocacoes() {

    comboLocacao.removeAllItems();

    locacoes = locacaoDAO.listar();

    for (Locacao locacao : locacoes) {

        if (!pagamentoDAO.existePagamento(locacao.getId())) {

            comboLocacao.addItem(
                locacao.getId()
                + " - "
                + locacao.getCliente().getNome()
                + " - "
                + locacao.getCarro().getMarca()
                + " "
                + locacao.getCarro().getModelo()
                + " - "
                + locacao.getCarro().getPlaca()
            );
        }
    }
}
        
        private Locacao obterLocacaoSelecionada() {

    if (comboLocacao.getSelectedItem() == null) {
        return null;
    }

    String texto =
        comboLocacao.getSelectedItem().toString();

    int id = Integer.parseInt(
        texto.split(" - ")[0]
    );

    for (Locacao locacao : locacoes) {

        if (locacao.getId() == id) {
            return locacao;
        }
    }

    return null;
}
        
        private void carregarPagamentos() {

    DefaultTableModel modelo =
        (DefaultTableModel) tabelaPagamentos.getModel();

    modelo.setRowCount(0);

    for (Pagamento pagamento : pagamentoDAO.listar()) {

        Locacao locacao = pagamento.getLocacao();

        modelo.addRow(new Object[]{
            locacao.getCliente().getNome(),

            locacao.getCarro().getMarca()
                + " "
                + locacao.getCarro().getModelo()
                + " - "
                + locacao.getCarro().getPlaca(),

            locacao.getQuantidadeDias(),

            String.format(
                "R$ %.2f",
                pagamento.getValor()
            ),

            pagamento.getFormaPagamento()
        });
    }
}

    private void limparCampos() {

    lblValor.setText("R$ 0,00");

    comboFormaPagamento.setSelectedIndex(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboLocacao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboFormaPagamento = new javax.swing.JComboBox<>();
        lblTituloCadastro1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPagamentos = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloCadastro.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblTituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadastro.setText("Histórico de Pagamentos");
        lblTituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTituloCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Locação:");

        comboLocacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLocacao.addActionListener(this::comboLocacaoActionPerformed);

        jLabel2.setText("Valor da Locação:");

        lblValor.setText("R$ 0,00");

        jLabel4.setText("Forma de Pagamento:");

        comboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTituloCadastro1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblTituloCadastro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadastro1.setText("Registrar Pagamento");
        lblTituloCadastro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTituloCadastro1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabelaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Carro", "Dias", "Valor", "Forma"
            }
        ));
        jScrollPane1.setViewportView(tabelaPagamentos);
        if (tabelaPagamentos.getColumnModel().getColumnCount() > 0) {
            tabelaPagamentos.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        btnPagar.setText("Registrar Pagamento");
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(this::btnFecharActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)))
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnPagar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTituloCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addGap(12, 12, 12)
                .addComponent(lblTituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        Locacao locacao = obterLocacaoSelecionada();

    if (locacao == null) {

        JOptionPane.showMessageDialog(
            this,
            "Selecione uma locação."
        );

        return;
    }

    String formaPagamento =
        comboFormaPagamento
            .getSelectedItem()
            .toString();

    Pagamento pagamento = new Pagamento(
        locacao,
        locacao.getValorTotal(),
        formaPagamento
    );

    pagamentoDAO.inserir(pagamento);

    JOptionPane.showMessageDialog(
        this,
        "Pagamento registrado com sucesso!"
    );

    limparCampos();

    carregarLocacoes();
    carregarPagamentos();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void comboLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocacaoActionPerformed
        Locacao locacao = obterLocacaoSelecionada();

    if (locacao != null) {

        lblValor.setText(
            String.format(
                "R$ %.2f",
                locacao.getValorTotal()
            )
        );

    } else {

        lblValor.setText("R$ 0,00");
    }
    }//GEN-LAST:event_comboLocacaoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> comboFormaPagamento;
    private javax.swing.JComboBox<String> comboLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloCadastro;
    private javax.swing.JLabel lblTituloCadastro1;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tabelaPagamentos;
    // End of variables declaration//GEN-END:variables
}
