/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolocadora;

/**
 *
 * @author Thiago Henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    public TelaPrincipal() {
        initComponents();
        setResizable(true);

    addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            redimensionarComponentes();
        }
    });
    }
    
    private void redimensionarComponentes() {

    int larguraOriginal = 800;
    int alturaOriginal = 600;

    int larguraAtual = getWidth();
    int alturaAtual = getHeight();

    double escalaX = (double) larguraAtual / larguraOriginal;
    double escalaY = (double) alturaAtual / alturaOriginal;

    btnClientes.setBounds(
        (int) (100 * escalaX),
        (int) (150 * escalaY),
        (int) (200 * escalaX),
        (int) (60 * escalaY)
    );

    btnCarros.setBounds(
        (int) (500 * escalaX),
        (int) (150 * escalaY),
        (int) (200 * escalaX),
        (int) (60 * escalaY)
    );

    btnLocacoes.setBounds(
        (int) (100 * escalaX),
        (int) (300 * escalaY),
        (int) (200 * escalaX),
        (int) (60 * escalaY)
    );

    btnPagamentos.setBounds(
        (int) (500 * escalaX),
        (int) (300 * escalaY),
        (int) (200 * escalaX),
        (int) (60 * escalaY)
    );

    btnSair.setBounds(
        (int) (300 * escalaX),
        (int) (450 * escalaY),
        (int) (200 * escalaX),
        (int) (60 * escalaY)
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnLocacoes = new javax.swing.JButton();
        btnCarros = new javax.swing.JButton();
        btnPagamentos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOCADORA AUTOBAHN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnLocacoes.setText("Locações");
        btnLocacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLocacoes.addActionListener(this::btnLocacoesActionPerformed);

        btnCarros.setText("Carros");
        btnCarros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCarros.addActionListener(this::btnCarrosActionPerformed);

        btnPagamentos.setText("Pagamentos");
        btnPagamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPagamentos.addActionListener(this::btnPagamentosActionPerformed);

        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSair.addActionListener(this::btnSairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
    this.setEnabled(false);

    TelaCliente tela = new TelaCliente();

    tela.setLocationRelativeTo(this);

    tela.addWindowListener(new java.awt.event.WindowAdapter() {

        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            setEnabled(true);
            toFront();
        }
    });

    tela.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnLocacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocacoesActionPerformed
    this.setEnabled(false);

    TelaLocacao tela = new TelaLocacao();

    tela.setLocationRelativeTo(this);

    tela.addWindowListener(
        new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(
                    java.awt.event.WindowEvent e) {

                setEnabled(true);
                toFront();
            }
        }
    );

    tela.setVisible(true);
    }//GEN-LAST:event_btnLocacoesActionPerformed

    private void btnCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrosActionPerformed
    this.setEnabled(false);

    TelaCarro tela = new TelaCarro();

    tela.setLocationRelativeTo(this);

    tela.addWindowListener(
        new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(
                    java.awt.event.WindowEvent e) {

                setEnabled(true);
                toFront();
            }
        }
    );

    tela.setVisible(true);
    }//GEN-LAST:event_btnCarrosActionPerformed

    private void btnPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentosActionPerformed
        this.setEnabled(false);

    TelaPagamento tela = new TelaPagamento();

    tela.setLocationRelativeTo(this);

    tela.addWindowListener(
        new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(
                    java.awt.event.WindowEvent e) {

                setEnabled(true);
                toFront();
            }
        }
    );

    tela.setVisible(true);
    }//GEN-LAST:event_btnPagamentosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarros;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnLocacoes;
    private javax.swing.JButton btnPagamentos;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
